### ISSUE TITLE
Windows 10 Python 3.7 inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by ghostcodekc** [BOfH85/VM_Snapshot_Manager#2]
Receiving an error when running VM_Snapshot_Manager.py in Windows 10. 

Error: 
```
Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
= RESTART: D:\Documents\Virtual Machines\Windows 10\VM_Snapshot_Manager\VM_Snapshot_Manager.py
Traceback (most recent call last):
  File "D:\Documents\Virtual Machines\Windows 10\VM_Snapshot_Manager\VM_Snapshot_Manager.py", line 12, in <module>
    import run as run
  File "D:\Documents\Virtual Machines\Windows 10\VM_Snapshot_Manager\snapcreate.py", line 36
    descfile = open(os.path.join(VMWorkstationPath, "snapshots", "")+VMDKName+"_"+timestamp+".txt","w")
                                                                                                      ^
TabError: inconsistent use of tabs and spaces in indentation
```

![pythonw_2020-07-18_11-35-34](https://user-images.githubusercontent.com/443960/87857250-e64e1200-c8ea-11ea-9734-7e9ce8d2a818.png)

**Comment by BOfH85** [comment]
thanks for checking,  i will look into it soon to fix it

**Comment by BOfH85** [comment]
please check again, issue should be fixed now

**Comment by BOfH85** [comment]
Fixed.
